
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ThinkPad
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        btn1.setText("1");
        btn2.setText("3");
        btn3.setText("5");
        btn4.setText("2");
        btn5.setText("4");
        btn6.setText("6");
        btn7.setText("8");
        btn8.setText("7");
        btn9.setText(" ");
    }

    public void chek() {
        if (btn1.getText().equals("1") && btn2.getText().equals("2")
                && btn3.getText().equals("3") && btn4.getText().equals("4")
                && btn5.getText().equals("5") && btn6.getText().equals("6")
                && btn7.getText().equals("7") && btn8.getText().equals("8")
                && btn9.getText().equals(" ")) {
            JOptionPane.showMessageDialog(frmMain.this, "!!!you won!!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn1.setLabel("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        btn2.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn2.setLabel("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        btn3.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn3.setLabel("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        btn4.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn4.setLabel("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 50));

        btn5.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn5.setLabel("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 50));

        btn6.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn6.setLabel("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 50));

        btn7.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn7.setLabel("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 50));

        btn8.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn8.setLabel("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 50));

        btn9.setFont(new java.awt.Font("Browallia New", 1, 18)); // NOI18N
        btn9.setLabel("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn1.getText().equals(" ")) {
            temp = btn2.getText();
            btn2.setText(" ");
            btn1.setText(temp);
        } else if (btn5.getText().equals(" ")) {
            temp = btn2.getText();
            btn2.setText(" ");
            btn5.setText(temp);
        } else if (btn3.getText().equals(" ")) {
            temp = btn2.getText();
            btn2.setText(" ");
            btn3.setText(temp);
        }
        
        chek ();
      }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn2.getText().equals(" ")) {
            temp = btn1.getText();
            btn1.setText(" ");
            btn2.setText(temp);
        } else if (btn4.getText().equals(" ")) {
            temp = btn1.getText();
            btn1.setText(" ");
            btn4.setText(temp);

    }//GEN-LAST:event_btn1ActionPerformed
    chek ();
    }
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn2.getText().equals(" ")) {
            temp = btn3.getText();
            btn3.setText(" ");
            btn2.setText(temp);
        } else if (btn6.getText().equals(" ")) {
            temp = btn3.getText();
            btn3.setText(" ");
            btn6.setText(temp);

        }
chek ();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn1.getText().equals(" ")) {
            temp = btn4.getText();
            btn4.setText(" ");
            btn1.setText(temp);
        } else if (btn5.getText().equals(" ")) {
            temp = btn4.getText();
            btn4.setText(" ");
            btn5.setText(temp);
        } else if (btn7.getText().equals(" ")) {
            temp = btn4.getText();
            btn4.setText(" ");
            btn7.setText(temp);
        }
chek ();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn2.getText().equals(" ")) {
            temp = btn5.getText();
            btn5.setText(" ");
            btn2.setText(temp);
        } else if (btn4.getText().equals(" ")) {
            temp = btn5.getText();
            btn5.setText(" ");
            btn4.setText(temp);
        } else if (btn6.getText().equals(" ")) {
            temp = btn5.getText();
            btn5.setText(" ");
            btn6.setText(temp);
        } else if (btn8.getText().equals(" ")) {
            temp = btn5.getText();
            btn5.setText(" ");
            btn8.setText(temp);
        }
chek ();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn3.getText().equals(" ")) {
            temp = btn6.getText();
            btn6.setText(" ");
            btn3.setText(temp);
        } else if (btn5.getText().equals(" ")) {
            temp = btn6.getText();
            btn6.setText(" ");
            btn5.setText(temp);
        } else if (btn9.getText().equals(" ")) {
            temp = btn6.getText();
            btn6.setText(" ");
            btn9.setText(temp);
        }
chek ();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn4.getText().equals(" ")) {
            temp = btn7.getText();
            btn7.setText(" ");
            btn4.setText(temp);
        } else if (btn8.getText().equals(" ")) {
            temp = btn7.getText();
            btn7.setText(" ");
            btn8.setText(temp);

        }
chek ();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn7.getText().equals(" ")) {
            temp = btn8.getText();
            btn8.setText(" ");
            btn7.setText(temp);
        } else if (btn5.getText().equals(" ")) {
            temp = btn8.getText();
            btn8.setText(" ");
            btn5.setText(temp);
        } else if (btn9.getText().equals(" ")) {
            temp = btn8.getText();
            btn8.setText(" ");
            btn9.setText(temp);
        }
chek ();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        String temp;
        if (btn6.getText().equals(" ")) {
            temp = btn9.getText();
            btn9.setText(" ");
            btn6.setText(temp);
        } else if (btn8.getText().equals(" ")) {
            temp = btn9.getText();
            btn9.setText(" ");
            btn8.setText(temp);

        }
chek ();
    }//GEN-LAST:event_btn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    // End of variables declaration//GEN-END:variables
}
